<?php

namespace app\libraries\games;

use app\models\GameRound;

class KenoLive extends Keno
{
    const NAME = 'keno4min';

    private $winCoef = [
        1 => [
            1 => 3
        ],
        2 => [
            1 => 1,
            2 => 10
        ],
        3 => [
            1 => 0,
            2 => 2,
            3 => 45
        ],
        4 => [
            1 => 0,
            2 => 1,
            3 => 10,
            4 => 80
        ],
        5 => [
            1 => 0,
            2 => 1,
            3 => 3,
            4 => 20,
            5 => 150
        ],
        6 => [
            1 => 0,
            2 => 0,
            3 => 2,
            4 => 15,
            5 => 60,
            6 => 500
        ],
        7 => [
            0 => 1,
            1 => 0,
            2 => 0,
            3 => 2,
            4 => 4,
            5 => 20,
            6 => 80,
            7 => 1000
        ],
        8 => [
            0 => 1,
            1 => 0,
            2 => 0,
            3 => 0,
            4 => 5,
            5 => 15,
            6 => 50,
            7 => 200,
            8 => 2000
        ],
        9 => [
            0 => 2,
            1 => 0,
            2 => 0,
            3 => 0,
            4 => 2,
            5 => 10,
            6 => 25,
            7 => 125,
            8 => 1000,
            9 => 5000
        ],
        10 => [
            0 => 2,
            1 => 0,
            2 => 0,
            3 => 0,
            4 => 0,
            5 => 5,
            6 => 30,
            7 => 100,
            8 => 300,
            9 => 2000,
            10 => 10000
        ]
    ];
    public function getAbbr()
    {
        return self::GAME_KENO_LIVE_ABBR;
    }

    public function getName()
    {
        return 'Keno Live';
    }

    public function getFactor($bet, $round_id)
    {
        parent::getFactor($bet, $round_id); // TODO: Change the autogenerated stub
        $results = GameRound::getResults(self::NAME, $round_id);
        $match = 0;

        if (is_array($results))
            $match = array_intersect($results, $bet);
        $countMatch = count($match);
        $countBet = count($bet);
        if (isset($this->winCoef[$countBet][$countMatch]))
            return $this->winCoef[$countBet][$countMatch];
        return 0;
    }
}